Azure/Industrial-IoT

services/src/Microsoft.Azure.IIoT.Services.OpcUa.Twin/src/container.json
Here is the code snippet from `Program.cs`:
```
public static IHostBuilder CreateHostBuilder(string[] args) {
return Host.CreateDefaultBuilder(args)
.UseAutofac()
.ConfigureWebHostDefaults(builder => builder
.UseUrls("http://*:9041")
.UseSerilog()
.UseStartup<Startup>()
.UseKestrel(o => o.AddServerHeader = false));
}
```
Changed `container.json` to expose port `9041` instead of `9042`.
=> Fixing port exposed by twin container to 9041 instead of 9042.

deploy.sh, deploy/scripts/aad-register.ps1, docs/deploy/howto-deploy-all-in-one.md, tools/scripts/acr-build.ps1, tools/scripts/docker-source.ps1
* Use the correct base image version for Windows 1809 image - add 1909
* Update documentation regarding Linux deployment
* Add deployment shell script to root.
=> Support deployment from Linux and fix Windows Gateway images not working

common.props, common/src/Microsoft.Azure.IIoT.Messaging.SignalR/src/Microsoft.Azure.IIoT.Messaging.SignalR.csproj, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Extensions/ApplicationRegistrationEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Extensions/DiscovererRegistrationEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Extensions/EndpointRegistrationEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Extensions/GatewayRegistrationEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Extensions/PublisherRegistrationEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Extensions/SupervisorRegistrationEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Services/ApplicationRegistry.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Services/EndpointRegistry.cs, docs/deploy/howto-deploy-aks.md
When calling the onboarding API the provided events do not contain all needed information to create an id that matches existing device entries.   This means existing entries get removed first, before same ones are re-added interrupting operation with existing device entities and causing unnecessary twin updates.
=> Fix onboarding id and hash calculation due to missing properties

azuredeploy.json, deploy/scripts/deploy.ps1, deploy/templates/azuredeploy.json, deploy/templates/azuredeploy.platform.json, deploy/templates/azuredeploy.simulation.json, docs/deploy/howto-deploy-all-in-one.md, docs/deploy/howto-deploy-local.md, docs/deploy/howto-deploy-modules-portal.md, docs/deploy/quickstart-gateway-installer.md, docs/deploy/readme.md
This fixes the issue that on some subscriptions certain vm sizes are disabled or not available.   The selection tries to find a comparable VM.   Also adds tagging of resource groups like connected factory.
=> Select VM Option and tagging resource group deployments

deploy/src/Microsoft.Azure.IIoT.Deployment/Configuration/ConsoleConfigurationProvider.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/ApplicationsManager.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Microsoft.Azure.IIoT.Deployment.csproj
Implemented:
* Upgraded Microsoft.Graph.Beta NuGet to 0.12.0-preview.
* ApplicationName should include alphanumeric characters and '-'.
This fixes:
* [[IAI] Underscore not acceptable in Azure App Service](https://msazure.visualstudio.com/One/_workitems/edit/6089296)
=> IAI: Upgraded Microsoft.Graph.Beta. Added checks for ApplicationName.

deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/AksMgmtClient.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/EventHubMgmtClient.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/IotHubMgmtClient.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/NetworkMgmtClient.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Microsoft.Azure.IIoT.Deployment.csproj
* Upgraded KubernetesClient NuGet package to 1.6.33.
* Upgraded AKS version to 1.15.7.
* Increased retention period (2 days) and number of partitions (4)  of both Event Hubs.
* Enabled incoming traffic on port 80 in NSG. This is required for next changes for `cert-manager`.
=> IAI: Minor infrastructure changes.

api/src/Microsoft.Azure.IIoT.Api/cli/Microsoft.Azure.IIoT.Cli.csproj, api/src/Microsoft.Azure.IIoT.Api/cli/Program.cs, common/src/Microsoft.Azure.IIoT.Auth.ActiveDirectory/src/Extensions/ConfigurationEx.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/IIoTEnvironment.cs, modules/src/Microsoft.Azure.IIoT.Modules.Diagnostic/cli/Program.cs, modules/src/Microsoft.Azure.IIoT.Modules.Discovery/cli/Program.cs, modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/cli/Program.cs, modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Twin/cli/Program.cs, samples/src/Microsoft.Azure.IIoT.App/src/Startup.cs, services/src/Microsoft.Azure.IIoT.Services.All/src/Startup.cs, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Events/src/Startup.cs, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Publisher.Edge/src/Startup.cs, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Publisher/src/Startup.cs, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry.Sync/src/Program.cs, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry/src/Startup.cs, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Twin.Gateway/src/Startup.cs, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Twin.History/src/Startup.cs, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Twin/src/Startup.cs, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Vault/src/Startup.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Events/src/Program.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry.Cdm/src/Program.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry/src/Program.cs
Purpose of this PR is to establish order of configuration providers so that any local configuration provider can override a value from KeyVault. This is required so that deployment through a Helm chart can use configuration deployed through `deploy.ps1` or IAI to KeyVault, but would still be able to override any value if needed. This will also help in local debugging when one wants to re-use most but not all values from KeyVault.
In general this is the order of increasing priority that I propose for configuration provider groups:
1. remote configuration provider (KeyVault)
2. local bulk configuration providers, `appsettings.json` and `.env`
3. local singular configuration providers, environment variables and command line arguments
More specifically, the order would look like this for …
=> Changing order of configuration providers.

deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/ApplicationsManager.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/IIoTEnvironment.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/50_industrial_iot_ingress.yaml
IAI still deploys `2.6.146` version of microservices, which means that changes related to `2.7.x` are not applicable.
Codes were copied from a commit prior to Pluggable authentication support (#402) (ef18f7a14a9e223c9df9f668a5c6f280ea4c1f01).
=> Reverting IAI changes introduced by plugable authentication support.

common/src/Microsoft.Azure.IIoT.Abstractions/src/Hub/Models/TwinProperty.cs, common/src/Microsoft.Azure.IIoT.Core/src/Hub/Extensions/DeviceTwinModelEx.cs, common/src/Microsoft.Azure.IIoT.Hub.Mock/src/Services/IoTHubServices.cs, common/src/Microsoft.Azure.IIoT.Hub.Module.Framework/src/Hosting/ModuleHost.cs, common/src/Microsoft.Azure.IIoT.Hub.Module.Framework/src/Services/IModuleHost.cs, common/src/Microsoft.Azure.IIoT.Hub.Module.Framework/tests/Common/ModuleHostHarness.cs, common/src/Microsoft.Azure.IIoT.Hub.Module.Framework/tests/Hosting/SettingsRouterTests.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Cdm/src/Services/CdmMessageProcessor.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Twin/src/Supervisor/Services/SupervisorServices.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Publisher/src/Services/PublisherJobService.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Extensions/DiscovererRegistrationEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Extensions/EndpointRegistrationEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Extensions/PublisherRegistrationEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Extensions/SupervisorRegistrationEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Services/DiscovererRegistry.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Services/EndpointRegistry.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Services/GatewayRegistry.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Services/PublisherRegistry.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Services/SupervisorRegistry.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/tests/Services/EndpointRegistryTests.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Testing/src/Tests/TestData/ReadArrayValueTests.cs, modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Twin/src/Controllers/EndpointSettingsController.cs, modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Twin/src/Controllers/SupervisorSettingsController.cs, modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Twin/src/ModuleProcess.cs, modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Twin/tests/Fixtures/TwinModuleFixture.cs, samples/src/Microsoft.Azure.IIoT.App/src/Services/Registry.cs
* Module upgrade does not update reported state correctly including connectivity status and twin activation status
* Heartbeat interval is not set in published nodes in list call.
* Temporarily eat ArgumentException in CDM processor during model.json creation to fix missing CSV persistency.
* Fix potential null byte array value returned by unit test server
=> Errors after Twin module upgrade and Heartbeat

deploy/helm/azure-industrial-iot/Chart.yaml, deploy/helm/azure-industrial-iot/README.md, deploy/helm/azure-industrial-iot/values.yaml
I have decided to change the way I reference other documents in Helm documentation, specifically documentation of our microservices.
Previously I was referencing them by the full URL to the `master` branch.This introduces several problems:
1. When viewing documentation of a specific version or branch/tag from GitHub repo, let's say `helm/0.2.0`, you are still redirected to docs in `master` branch. This is problematic as some of the microservices either do not exist any more or they may have been renamed. In both cases links are invalidated.
2. Similar problem exists when viewing published charts in Helm repositories. They also reference documents in `master` branch which do not exist any more.
Here is my plan going forward:
1. Use relative links in GitHub repo. This will make sure that …
=> Helm: Upgraded Azure Industrial IoT components to 2.7.105 version.

deploy/scripts/deploy.ps1, deploy/templates/azuredeploy.configuration.json, deploy/templates/azuredeploy.edge.json, deploy/templates/azuredeploy.json, deploy/templates/azuredeploy.minimum.json, deploy/templates/azuredeploy.platform.json, deploy/templates/azuredeploy.simulation.json, deploy/templates/azuredeploy.standard.json, deploy/templates/azuredeploy.workbook.json
Work done:
* Adding tags to ARM templates.
* Generating value of `IoTSuiteType` tag in deploy.ps1.
`IoTSuiteType` tag will have the following value: `AzureIndustrialIoT-<docker_image_tag>-PS1`. This aligns with the value generated by IAI, which is `AzureIndustrialIoT-<docker_image_tag>-IAI`.
=> Adding IoTSuiteType tag to PS1 deployment.

deploy/scripts/deploy.ps1, deploy/templates/azuredeploy.edge.json, deploy/templates/azuredeploy.json, deploy/templates/azuredeploy.simulation.json, readme.md
Now `deploy.ps1` script will select a VM SKU with at least 1 core and 2 GB memory instead of defaulting to `Standard_B1ms` for simulation VM. This is required because `Standard_B1ms` SKU is not available in all subscriptions.
=> PS1: Added logic for simulation VM selection instead of Standard_B1ms.

azure-pipelines.yml, tools/templates/ci.yml, tools/templates/iiot_deployment_linux.yml, tools/templates/iiot_deployment_mac.yml, tools/templates/iiot_deployment_win.yml
Here I am uploading `Microsoft.Azure.IIoT.Deployment` (IAI) binaries to a public Blob Container after build.
The following files will be uploaded from each host OS:
* `Microsoft.Azure.IIoT.Deployment.exe` on Windows or `Microsoft.Azure.IIoT.Deployment` on Linux an macOS
* `Microsoft.Azure.IIoT.Deployment.pdb`
* `Microsoft.Azure.IIoT.Deployment.md5`
I will be using `binaries` Blob Container in `azureiiot` Storage Account for storing those files.
The Blobs will have the following general naming scheme: `<branch_name>/<version>/<os_version>/<filename>`
A sample of this will be `kakostan/bin_upload/2.7.125/win-x64/Microsoft.Azure.IIoT.Deployment.exe`, where `kakostan/bin_upload` is name of my branch, `2.7.125` is the version of binaries and `win-x64` specifies OS and its bitness.
The …
=> IAI: Uploading IAI binaries to Azure Blob Container after build.

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Extensions/GatewayRegistrationEx.cs, samples/src/Microsoft.Azure.IIoT.App/src/Pages/Gateways.razor, samples/src/Microsoft.Azure.IIoT.App/src/Shared/MainLayout.razor
- Gateway page didn't show the connection status, because the value has never been set.
- The error message from the home page is removed.
=> Gateway connection status fix

services/src/Microsoft.Azure.IIoT.Services.OpcUa.Publisher/src/Runtime/Config.cs
`WorkerDatabase` requires a `IWorkerDatabaseConfig` config to be initialized. This change is making sure that `Config` of Opc-Publisher-Service implements this interface.
This was causing an error when  calling `/v2/workers` endpoint:
```
{
"ClassName": "Autofac.Core.DependencyResolutionException",
"Message": "An exception was thrown while activating Microsoft.Azure.IIoT.Agent.Framework.Storage.Database.WorkerDatabase.",
"Data": {
"ActivatorChain": "Microsoft.Azure.IIoT.Agent.Framework.Storage.Database.WorkerDatabase"
},
"InnerException": {
"ClassName": "Autofac.Core.DependencyResolutionException",
"Message": "None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Microsoft.Azure.IIoT.Agent.Framework.Storage.Database.WorkerDatabase' can …
```
=> Added IWorkerDatabaseConfig interface to fix WorkerDatabase creation.

services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry.Sync/src/HostStarterService.cs, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry.Sync/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry.Sync.csproj, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry.Sync/src/Program.cs, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry.Sync/src/Runtime/ServiceInfo.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Events/src/HostStarterService.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Events/src/Microsoft.Azure.IIoT.Services.Processor.Events.csproj, services/src/Microsoft.Azure.IIoT.Services.Processor.Events/src/Program.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Events/src/Runtime/ServiceInfo.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Events/src/StarterService.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Onboarding/src/HostStarterService.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Onboarding/src/Microsoft.Azure.IIoT.Services.Processor.Onboarding.csproj, services/src/Microsoft.Azure.IIoT.Services.Processor.Onboarding/src/Program.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Onboarding/src/Runtime/ServiceInfo.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry.Cdm/src/HostStarterService.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry.Cdm/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry.Cdm.csproj, services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry.Cdm/src/Program.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry.Cdm/src/Runtime/ServiceInfo.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry/src/HostStarterService.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry.csproj, services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry/src/Program.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry/src/Runtime/ServiceInfo.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Tunnel/src/HostStarterService.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Tunnel/src/Microsoft.Azure.IIoT.Services.Processor.Tunnel.csproj, services/src/Microsoft.Azure.IIoT.Services.Processor.Tunnel/src/Program.cs, services/src/Microsoft.Azure.IIoT.Services.Processor.Tunnel/src/Runtime/ServiceInfo.cs
Docs: [.NET Generic Host](https://docs.microsoft.com/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1)
* Using ASP.NET Core generic host for hosting event processor.
* Added Application Insights dependency tracking.
* Minor refactoring in Microsoft.Azure.IIoT.Services.Processor.Events.
* Generic host for Microsoft.Azure.IIoT.Services.Processor.Onboarding.
* Minor refactoring.
* Generic host for Microsoft.Azure.IIoT.Services.Processor.Telemetry.Cdm..
* Generic host for Microsoft.Azure.IIoT.Services.Processor.Telemetry.
* Generic host for Microsoft.Azure.IIoT.Services.Processor.Tunnel.
* Generic host for Microsoft.Azure.IIoT.Services.OpcUa.Registry.Sync.
One thing to note here is that I've removed `HostAutoStart` from container builder of event processors and I have delegated …
=> Changed event processors to use .NET generic hosts.

azure-pipelines.yml, tools/templates/iiot_deployment_win.yml, tools/templates/nuget.yml
This makes sure that stages other than `build` run only if `build` stage has succeeded.
=> Making sure that CI/CD stages run only if their dependencies have succeeded.

deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/IIoTEnvironment.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/StorageMgmtClient.cs
Azure Industrial IoT components `<2.8.5` (#613) version lack processing of `PCS_ADLSG2_CONNSTRING` configuration parameters. Thus `telemetry-cdm-processor` deployed by current version of IAI does not receive enough parameters to connect to ADLS Gen2 storage account.
To provide connection details for ADLS Gen2 storage account I've added `PCS_ADLSG2_ACCOUNT`, `PCS_ADLSG2_ACCOUNT_KEY` and `PCS_ADLSG2_ENDPOINTSUFFIX` fallback parameters.
=> IAI: Fixing configuration for CDM processor.

deploy/helm/azure-industrial-iot/templates/26_onboarding_deployment.yaml, deploy/helm/azure-industrial-iot/templates/27_sync_deployment.yaml, deploy/helm/azure-industrial-iot/templates/33_events-processor_deployment.yaml, deploy/helm/azure-industrial-iot/templates/38_telemetry_cdm_processor_deployment.yaml, deploy/helm/azure-industrial-iot/templates/39_telemetry_processor_deployment.yaml, deploy/helm/azure-industrial-iot/templates/40_tunnel_processor_deployment.yaml
I've changed deployment YAML files of non-API services to expose ports that should be used for Prometheus metrics scraping. The ports are exposed conditionally when scraping of metrics is enabled.
Modified services are the following:
- onboarding
- sync
- eventsProcessor
- telemetryProcessor
- telemetryCdmProcessor
- tunnelProcessor
=> Helm: Exposing metrics ports for non-API services. 

deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/AksMgmtClient.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/AzureResourceManager.cs
I've introduced logic to select latest patch version of `1.16.x` Kubernetes for AKS.
This should solve issues that we were facing previously, when a specific version of Kubernetes has been deprecated from AKS, such as #593.
=> IAI: Using latest 1.16.x patch version of Kubernetes in AKS.

common/src/Microsoft.Azure.IIoT.Auth.ActiveDirectory/src/Extensions/ConfigurationEx.cs, common/src/Microsoft.Azure.IIoT.Auth.ActiveDirectory/src/Runtime/AadUserKeyVaultConfig.cs, deploy/scripts/aad-register.ps1, deploy/scripts/deploy.ps1, deploy/templates/azuredeploy.json, deploy/templates/azuredeploy.platform.json, docs/deploy/howto-deploy-all-in-one.md, readme.md
* Added parameter authTenantId to deploy.ps1 to specify AAD tenant used for authentication (PCS_AUTH_TENANT)
* When using authTenantId for user authentication, key vault uses PCS_MSI_TENANT
* Modified AadUserKeyVaultConfig.cs -> TenantId to prefer PCS_MSI_TENANT and fallback to PCS_AUTH_TENANT to allow local debugging using VS
* Added parameter tenantId to dpeloy.ps1 to filter subscriptions based on specified tenant
* Added documentation of new parameters and options on how to solve consent granting issue
* Tested the following scenarios:
1. Deploy to MS subscription specifying authTenantId for new custom AAD
2. Deploy to OPCWALL subscription using default AAD
* Verified that key vault contained valid access policies for managed ID and my user account (for debugging in VS)
* Verified that …
=> Add support to deploy with specific auth tenant

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Publisher/src/Services/PublisherJobService.cs, version.json
The following environment variables can be set to configure the batch trigger interval and batch size.
The environment variable PCS_DEFAULT_PUBLISH_JOB_BATCH_INTERVAL can be set as milliseconds from 100 to 3,600,000 ms.  Other values (e.g. <= 0) will result in the default value of 10,000 ms (10 seconds).
The environment variable PCS_DEFAULT_PUBLISH_JOB_BATCH_SIZE can be set as a value between 2 and 1000.   Every other value will result in the default of 50 subscription notifications per batch being set.
The environment variables must be set on the Publisher container Pod to affect the settings in all job configurations from this point on that are performed using the Publisher REST API.  (iot/opc-publisher-service).
The change is in the PublisherJobService Adapter, which adapts from 2.7 …
=> Allow environment variable configuration of batch size and interval. 

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/DataFlowProcessingEngine.cs
- Under certain conditions the batch interval timer is not properly recharged.
Fix by recharging timer on every timer callback instead of recharge in the Dataflow callback.
=> Fix for batch trigger interval timer

api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Extensions/ModelExtensions.cs, api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Models/EngineConfigurationApiModel.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/DataFlowProcessingEngine.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Extensions/WriterGroupModelEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/IEngineConfiguration.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Models/LegacyCliModel.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Runtime/WriterGroupJobConfig.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Storage/PublishedNodesJobConverter.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Publisher/src/Services/PublisherJobService.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Extensions/PublisherConfigModelEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/EngineConfigurationModel.cs, modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Runtime/LegacyCliConfigKeys.cs, modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Runtime/LegacyCliOptions.cs
This is cumulative PR for batching related changes that happened on `release/2.7.180` branch:
From @koepalex: Drop iot hub messages if exceed the maximum limit (#652):
* Drop iot hub messages if exceed the maximum limit
* limit for outgoing ioT Hub messages set to 200 (hardcoded) which equals 50 MB memory
* extend diagnostics output with number of dropped messages
* Make max number of IoT D2C messages configurable
* configurable via environment variable `PCS_DEFAULT_PUBLISH_MAX_OUTGRESS_MESSAGES`
* configurable via cli parameter `mom` or `maxoutgressmessages`
* implemented review comments
* aligned XML comments
* cli parameter shot form changed from _mom_ to **om**
From @mregen: Fix for batch trigger interval timer, which is not properly recharged under certain conditions. (#654)
* Under …
=> Enabling configuration of batch size and interval.

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/NetworkMessageEncoder.cs
Updated the calculation of average Notifications per Message for Pub/Sub encoded messages correctly. 
One Pub/Sub message contains array of messages and each of those messages have array of value changes (notifications) as Payload.
=> fix avg notification per message for Pubsub

api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Extensions/ModelExtensions.cs, api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Models/EngineConfigurationApiModel.cs, common/src/Microsoft.Azure.IIoT.Abstractions/src/PcsVariable.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/DataFlowProcessingEngine.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/FileSystemMessageSink.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/IoTHubMessageSink.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/MonitoredItemMessageEncoder.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/NetworkMessageEncoder.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/WriterGroupMessageSource.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Extensions/WriterGroupModelEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/IEngineConfiguration.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/IMessageEncoder.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/IMessageSink.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/IMessageTrigger.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Models/LegacyCliModel.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Runtime/WriterGroupJobConfig.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Storage/PublishedNodesJobConverter.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Publisher/src/Services/PublisherJobService.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Extensions/PublisherConfigModelEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/EngineConfigurationModel.cs, modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Runtime/LegacyCliConfigKeys.cs, modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Runtime/LegacyCliOptions.cs
* Reformat diag info for easier readability and consistency
* Added units to diag info values
* Corrected term "outgress" to "egress" including option em|maxegressmessagequeue
* Changed default egress queue from 20 (max 50 MB) to 8192 (max 2 GB), as it behaved better during local debugging in VS, otherwise too many messages are dropped
* Some cosmetic improvements
=> Improvements to diag info

tools/templates/sdl.yml
Hard-coded .NET version as `3.1.302` for SDL Task. Need to revert change back to `3.1.x` after [this](https://developercommunity.visualstudio.com/content/problem/1145815/net-coremsbuild-tooling-not-finding-right-version.html) bug is fixed.
=> Temporary fix for SDL Task.

common/src/Microsoft.Azure.IIoT.Core/src/Utils/Retry.cs, common/src/Microsoft.Azure.IIoT.Core/tests/Utils/RetryTests.cs
Process will now stop retrying after `maxRetry` attempts even if it keeps getting `ITransientException`. With the previous condition, if the error keeps being `ITransientException`, then the method will keep delaying and will never throw.
=> Changed retry logic to stop also for repeated ITransientException.

common/src/Microsoft.Azure.IIoT.Hub.Module.Client/src/Default/IoTSdkFactory.cs
Applying changes by @koepalex in this [PR](https://github.com/Azure/Industrial-IoT/pull/694) on `master`.
Changes:
* Extend ConnectionString to handle GatewayHostName
* Revert "Extend ConnectionString to handle GatewayHostName": This reverts commit 00593ad625a42b2b0b8ee06bc61cbae9414659ae.
* Quickfix - adding gateway host name to connection string if set via environment variable
* Set GatewayHostName only if not already contained in connection string
=> Reactivate transparent gateway mode

common/src/Microsoft.Azure.IIoT.Core/src/Hub/Client/IoTHubHttpClientBase.cs
Using same API version as client SDKs.
This is to fix the error that we saw in North Europe and later in Southeast Asia that cause IoT Hub REST API calls to return with the following error:
```
{
"Message":"ErrorCode:InvalidProtocolVersion;BadRequest",
"ExceptionMessage":"Tracking ID:113a1b7dd04946059412a08842d2be71-G:6-TimeStamp:09/07/2020 14:46:08"
}
```
=> Using same API version as client SDKs.

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Publisher/src/Deploy/IoTHubPublisherDeployment.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Deploy/IoTHubDiscovererDeployment.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Twin/src/Deploy/IoTHubSupervisorDeployment.cs
* added host bind mounts for layered IoT Edge deployments
* the PkiRootPath is set to the same mount storage for all edge modules so that the modules can share the same pki store
=> bind mounts for layered Iot Edge deployments

Industrial-IoT.sln, common/src/Microsoft.Azure.IIoT.Agent.Framework/src/IJobOrchestratorEndpointConfig.cs, common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Jobs/Hub/JobOrchestratorEndpointSync.cs, common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Jobs/Runtime/JobOrchestratorEndpointConfig.cs, common/src/Microsoft.Azure.IIoT.Agent.Framework/tests/Jobs/Hub/JobOrchestratorEndpointSyncTests.cs, common/src/Microsoft.Azure.IIoT.Agent.Framework/tests/Microsoft.Azure.IIoT.Agent.Framework.Tests.csproj, common/src/Microsoft.Azure.IIoT.Core/src/Http/HttpClient.cs, common/src/Microsoft.Azure.IIoT.Core/src/Hub/Auth/Services/TwinIdentityTokenUpdater.cs, common/src/Microsoft.Azure.IIoT.Core/tests/Hub/Auth/Services/TwinIdentityTokenUpdaterTests.cs, common/src/Microsoft.Azure.IIoT.Core/tests/Utils/RetryTests.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Services/ActivationSyncHost.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/tests/Services/ActivationSyncHostTests.cs, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry.Sync/src/Runtime/Config.cs
Applying changes in #731 on `release/2.7.180` branch.
Changes:
* Changed `HttpClient` class to throw `HttpRequestException` on timeout.
* Passing linked cancellation token downstream.
* Changed `OperationCanceledException` exception handling to check for token cancellation.
* Made job orchestrator URL synchronization interval configurable.
* Added tests for exception handling in `JobOrchestratorEndpointSync` class.
* Added tests for exception handling in `ActivationSyncHostclass`.
* Added tests for exception handling in `TwinIdentityTokenUpdater` class.
* Fixed minor bug in `JobOrchestratorEndpointSync`.
* Fixing a race condition on Dispose() in `JobOrchestratorEndpointSync`.
* Fixing a race condition on Dispose() in `ActivationSyncHost`.
* Fixing a race condition on Dispose() in …
=> Changed HttpClient class to throw HttpRequestException on timeout.

deploy/scripts/deploy.ps1
After this change, failure to open a web browser to access Engineering Tool will not cause deployment to fail. The URL of the Engineering Tool is already printed to output before we try to open a web browser, so no additional logs are added in case of error. The log with the URL looks like this:
```
The deployed application can be found at:
https://kakostan-wsl-test-100.azurewebsites.net
```
=> Ignore failure to open a web browser in deploy.ps1.

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/DataFlowProcessingEngine.cs
renaming the metric #Encoder avg Notification/Message  to #Encoder avg ValueChanges/Message because of misleading information
=> metric name fix

common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Agent/Default/Worker.cs, common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Agent/Default/WorkerSupervisor.cs, common/src/Microsoft.Azure.IIoT.Agent.Framework/src/IWorkerSupervisor.cs, common/src/Microsoft.Azure.IIoT.Agent.Framework/tests/Worker/WorkerSupervisorTests.cs
**Issue:**
The number of Worker within publisher can't be reduced. 
Calling *PATCH /registry/v2/publishers/{publisherId}* with smaller number of MaxWorker will not result in terminating worker. Example payload:
```json
{
"configuration": {
"maxWorkers": 4
}
}
```
**Solution:**
WorkerSupervisor have to also reduce number of Worker within EnsureWorker method.
**Others:**
* Updated IWorkerSupervisor interface
* Removed `CreateWorker` because it wasn't used externally
* Removed `StopWorker(WorkerId)` because it wasn't used externally
* Added getter `int NumberOfWorker` to be used from tests
* Added tests for WorkerSupervisor
=> WorkerSupervisor enable the reduction of Worker 

modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/ModuleProcess.cs
**Issue:**
SessionManager can be null, the current handling `await sessionManager?.StopAsync()` isn't sufficient, because the await will be called on null, which causes NullReferenceException.
**Solution:**
Await empty task, if sessionManager is null.
=> Avoid NullReferenceException in ModuleProcess

common/src/Microsoft.Azure.IIoT.AspNetCore.SignalR/src/Microsoft.Azure.IIoT.AspNetCore.SignalR.csproj, common/src/Microsoft.Azure.IIoT.AspNetCore/src/Microsoft.Azure.IIoT.AspNetCore.csproj, common/src/Microsoft.Azure.IIoT.Http.SignalR/src/Microsoft.Azure.IIoT.Http.SignalR.csproj, common/src/Microsoft.Azure.IIoT.Messaging.SignalR/src/Microsoft.Azure.IIoT.Messaging.SignalR.csproj, samples/src/Microsoft.Azure.IIoT.App/src/Microsoft.Azure.IIoT.App.csproj, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Events/tests/Microsoft.Azure.IIoT.Services.OpcUa.Events.Tests.csproj, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry/tests/Microsoft.Azure.IIoT.Services.OpcUa.Registry.Tests.csproj, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Twin.History/tests/Microsoft.Azure.IIoT.Services.OpcUa.Twin.History.Tests.csproj, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Twin/tests/Microsoft.Azure.IIoT.Services.OpcUa.Twin.Tests.csproj, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Vault/tests/Microsoft.Azure.IIoT.Services.OpcUa.Vault.Tests.csproj
Versions of the following NuGet packages have been bumped from `3.1.5` to `3.1.9`:
* Authentication:
* `Microsoft.AspNetCore.Authentication.AzureAD.UI`
* `Microsoft.AspNetCore.Authentication.OpenIdConnect`
* `Microsoft.AspNetCore.Authentication.JwtBearer`
* Components:
* `Microsoft.AspNetCore.Components.Web`
* DataProtection:
* `Microsoft.AspNetCore.DataProtection.AzureKeyVault`
* `Microsoft.AspNetCore.DataProtection.AzureStorage`
* Mvc:
* `Microsoft.AspNetCore.Mvc.NewtonsoftJson`
* `Microsoft.AspNetCore.Mvc.Testing`
* SignalR:
* `Microsoft.AspNetCore.SignalR.Client`
* `Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson`
* `Microsoft.AspNetCore.SignalR.Protocols.MessagePack`
=> Bumped several Microsoft.AspNetCore.* NuGet packages from 3.1.5 to 3.1.9.

common/src/Microsoft.Azure.IIoT.AspNetCore/src/Microsoft.Azure.IIoT.AspNetCore.csproj, common/src/Microsoft.Azure.IIoT.Core/src/Microsoft.Azure.IIoT.Core.csproj
Versions of the following NuGet packages have been bumped from `3.1.5` to `3.1.9`:
* `Microsoft.Extensions.Caching.Abstractions`
* `Microsoft.Extensions.Hosting`
* `Microsoft.Extensions.Http`
* `Microsoft.Extensions.Diagnostics.HealthChecks`
=> Bump Microsoft.Extensions.* packages from 3.1.5 to 3.1.9.

common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Agent/Default/Worker.cs
**Issue:** there are multiple places were the JobProcessor is set to null. Which can lead to NullReferenceException in Cancel method e.g. when job continuation is triggered.
**Solution:** Check for null in Cancel method and update worker status on every place were it set to null to have the information in cosmosdb in sync.
=> Avoid NullReferenceException in case of job continuation

tools/scripts/acr-build.ps1
- prelease version didn't show up in the tags
=> Typo in prereleaseversion ACR script

.github/dependabot.yml
This will allow to consolidate the nuget package updates
=> Direct dependabot clutter to a 'nuget' branch

modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Runtime/LegacyCliConfigKeys.cs, modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Runtime/LegacyCliOptions.cs
the root cause of this bug is the explicit setting of the parameter --ms=0.
This parameter should configure the message size for IoTHuB, but it wrongly set also the message size in the publisher/client connection.  
This parameter was wrongly used to set the MaxMessageSize in TransportQuotaConfig in EndpointConfiguration
=> fix bug: Fails when more 468 values are added to publisher

deploy/src/Microsoft.Azure.IIoT.Deployment/Configuration/HelmSettings.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/AksMgmtClient.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Microsoft.Azure.IIoT.Deployment.csproj, deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/IIoTDeploymentTags.Designer.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/IIoTDeploymentTags.resx, deploy/src/Microsoft.Azure.IIoT.Deployment/appsettings.json, docs/deploy/howto-deploy-aks.md
Changes:
* Removed unused `KubernetesClient` NuGet.
* Bumped AKS version to `1.18`, fallback version is `1.18.10`.
* Bumped deployed platform version to `2.7.199` from `2.7.170`.
Note: AKS is [deprecating](https://github.com/Azure/AKS/releases/tag/2020-10-26) `1.16.*` versions of Kubernetes.
=> IAI: Upgraded AKS to 1.18 and platform to 2.7.199.

deploy.cmd, deploy.sh, deploy/scripts/deploy.ps1
The code has been tested with the following commands on Windows:
```bash
.\deploy.cmd -version "2.7.199"
.\deploy.cmd -version "2.7.199" -type all
.\deploy.cmd -type all -version "2.7.199"
.\deploy.cmd -version
```
The code has been tested with the following commands on Linux:
```bash
./deploy.sh -version "2.7.199"
./deploy.sh -version "2.7.199" -type all
./deploy.sh -type all -version "2.7.199"
./deploy.sh -version
```
=> Fixing parsing of version in deployment scripts.

deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/scripts/jumpbox.sh
The default timeout of installing helm charts is 5min. Automated end to end testing shows that this time is not enough in some cases. To be safe, I changed to timeout to 30min.
=> Extend timeout for installing helm charts via IAI

deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/deployments/jumpbox-vm.json
To fix a known issue with delay of Service Principal creation, we have added  `principalType` field in role assignment properties.
Here are a few relevant links that point to this solution:
* Stack Overflow: [Sometimes ARM template will throw PrincipalNotFound Error when Working with User-assigned Managed Identity](https://stackoverflow.com/questions/60516853/sometimes-arm-template-will-throw-principalnotfound-error-when-working-with-user)
* Microsoft Docs: [Add Azure role assignments using Azure Resource Manager templates](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-template#new-service-principal)
=> IAI: Added principalType to role assignment.

deploy.cmd, deploy.sh, deploy/scripts/deploy.ps1
Applying changes in (#892) for `2.7.20x` release.
Changes:
* Fixing parsing of version in deployment scripts.
* Moved logic of default version to deploy.ps1.
=> Fixing parsing of version in deployment scripts. (#892)

common/src/Microsoft.Azure.IIoT.Hub.Module.Framework/src/ModuleFramework.cs
-regression due to recent cleanup effort, adding missing DI dependency for IHttpClient causing restarts
https://msazure.visualstudio.com/One/_workitems/edit/9048620
=> Fix OPC Publisher keeps restarting

deploy/scripts/deploy.ps1, thirdpartynotices.txt, version.json
The BOM got removed from the deploy.ps1 script and would not parse anymore.   Adding it back.
=> BOM missing from ps1

common/src/Microsoft.Azure.IIoT.Serializers.NewtonSoft/src/Default/NewtonSoftJsonSerializer.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/LegacyJobOrchestrator.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Storage/PublishedNodesJobConverter.cs
Changes to published nodes files, currently ending up in unexpected behavior. 
* Handling error while deserialization published nodes json
* Don't set MaxWorker if there are not work items in published nodes json
* Improved logging while reloading published nodes json
=> Dynamic changes to published nodes json file (under linux)

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/NetworkMessageEncoder.cs
With sample published nodes json:
```json
[
{
"DataSetWriterGroup": "myAsset_1",
"DataSetWriterId" : "myDataSetWriter_1",
"DataSetPublishingInterval": 1000,
"EndpointUrl": "opc.tcp://opcplc:50000",
"UseSecurity": false,
"OpcNodes": [
{
"Id": "ns=2;s=FastUInt4981",
"DataSetFieldId":"myFastNode_1",
"OpcSamplingInterval": 1000
}]
}
]
```
the output should be
```json
{
"body": {
"MessageId": "630",
"MessageType": "ua-data",
"PublisherId": "Standalone-test-device_",
"DataSetWriterGroup": "myAsset_1",
"Messages": [
{
"DataSetWriterId": "myDataSetWriter_1",
"SequenceNumber": 630,
"MetaDataVersion": {
"MajorVersion": 1,
"MinorVersion": 0
},
"Timestamp": "2021-01-16T10:09:42.5131106Z",
"Payload": {
"myDTDLFastNode_1": {
"Value": 8921,
"SourceTimestamp": "2021-01-16T10:09:41.9769585Z", …
```
=> Use DataSetFieldId from published nodes json, from PubSub encoder

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/NetworkMessageEncoder.cs
**Problem:**
Using DataSetFieldId as identifier for PubSub payload is not working if published node was defined by Expanded Node ID from published nodes json.
**Expected:**
node id and expected node id should work
**Implementation:**
Match subscription notification to "meta description" (DataSetSource) not only be direct compare of NodeId also by compare of expanded Node Id.
=> Extend matching of subscription notification to published nodes 

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/LegacyJobOrchestrator.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/tests/Engine/LegacyJobOrchestratorTests.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/tests/Engine/pn_assets.json, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/tests/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Tests.csproj
**Problems:**
* Jobs generated out of published nodes file, all have same id
* GetAvailableJobAsync didn't lock when called from multiple worker
* SendHeartbeatAsync logic with "dirty flag" (_updated) error prone
**Solutions:**
* Use DataGroupId as job id (if available) otherwise include GUID
* Add lock and exception handling to GetAwailableJobAsync
* SendHeartbeatAsync just working on _assignedJobs dictionary
**Tests:**
* added test to verify job ids are unequal
=> published nodes with different "groups/assets" for same endpoint causing closing and reopening of sessions

deploy/helm/azure-industrial-iot/README.md, docs/architecture-details.md, docs/architecture-flow.md, docs/deploy/howto-deploy-all-in-one.md, docs/deploy/howto-deploy-modules-portal.md
Changes:
* Added release branch name to git clone command in deployment instructions. This transfers the changes that we already have in the `master` branch to `release/2.7.206` branch to eliminate deployment issues for customers.
* Removed double whitespaces in text and trailing whitespaces.
=> Added release branch name to git clone command.

deploy/helm/azure-industrial-iot/README.md, docs/deploy/howto-add-aks-to-ps1.md, docs/deploy/howto-deploy-helm.md
Updated the following documentation pages to include details about `0.3.2` version of `azure-industrial-iot` Helm chart:
* `docs/deploy/howto-add-aks-to-ps1.md`
* `docs/deploy/howto-deploy-helm.md`
Removed some trailing whitespaces.
=> Helm: Added details about 0.3.2 version of the chart.

api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Adapter/PublisherServicesApiAdapter.cs, api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Extensions/ModelExtensions.cs, api/src/Microsoft.Azure.IIoT.OpcUa.Api.Publisher/src/Models/PublishBulkResponseApiModel.cs, common/src/Microsoft.Azure.IIoT.Agent.Framework/src/IJobService.cs, common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Jobs/Default/DefaultJobService.cs, common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Storage/Database/Services/JobDatabase.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Publisher/src/Services/PublisherJobService.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Publisher/tests/Services/PublisherJobServiceTests.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/IPublishServices.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/PublishBulkResultModel.cs, services/src/Microsoft.Azure.IIoT.Services.OpcUa.Publisher/src/Controllers/PublishController.cs
Azure DevOps PBI: [[REST API] unpublishing an unknown node, doesn't indicate an error](https://msazure.visualstudio.com/One/_workitems/edit/9056770)
Changes:
* `PublisherJobService.NodePublishStopAsync()` method has been modified to throw an exception when a node that is not present in any jobs is unpublished.
* `PublisherJobService.NodePublishBulkAsync()` method has been modified to report `404/NotFound` status code for unpublish node requests for nodes that are not present in any jobs.
* `PublishController` controller class has been modified to report `404/NotFound` status codes when appropriate.
* `DefaultJobService.DeleteJobAsync()` method has been modified to throw an exception when it is called with an unknown `jobId`.
* Added `CancellationToken` to `IPublishServices` interface.
=> Reporting errors via return codes when a node that is not present in any jobs is unpublished.

deploy/src/Microsoft.Azure.IIoT.Deployment/Configuration/HelmSettings.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/IIoTDeploymentTags.Designer.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/IIoTDeploymentTags.resx, deploy/src/Microsoft.Azure.IIoT.Deployment/appsettings.json, docs/deploy/howto-add-aks-to-ps1.md, docs/deploy/howto-deploy-aks.md
Changes:
* Upgraded Helm chart version to `0.3.2` and platform to `2.7.206`.
* Changed Helm chart and platform versions in documentation.
This will allow us to use `0.3.2` version of the Helm chart in E2E tests for orchestrated mode.
=> IAI: Upgraded Helm chart version to 0.3.2 and platform to 2.7.206.

tools/scripts/acr-build.ps1, tools/scripts/acr-prune.ps1
Unable to set BUILD_REGISTRY with environment variable. Syntax should be `$Env:<variable-name>`.
=> Fix build registry typo in ACR scripts

e2e-tests/IIoTPlatform-E2E-Tests/Orchestrated/A_PublishSingleNodeOrchestratedTestTheory.cs, e2e-tests/IIoTPlatform-E2E-Tests/Orchestrated/B_PublishMultipleNodesOrchestratedTestTheory.cs, e2e-tests/IIoTPlatform-E2E-Tests/TestHelper.Registry.cs
The e2e tests fail because the endpoint cannot be activated on the first request. While we are investigating that, the workaround is to retry the request.
=> Retry to activate endpoint when the request fails

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
When the flag _FetchOpcNodeDisplayName_ (--fd) is set, it has an undesirable impact on the published events. Fixed by filtering the monitored items when the subscription wrapper is asked to resolve display names.
The flag is intended for OpcNodes and not OpcEvents: "... flag whether to fetch the display names of the nodes." (from LegacyCliConfigKeys).
=> Fix FetchOpcNodeDisplayName flag for events

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Extensions/MonitoredItemNotificationModelEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Encoders/Models/EncodeableDictionary.cs
The EncodeableDictionary is only used for encoding event values. It was encoded as an array on a property called EventFields. There are already classes to encode arrays, but it also is not reflective of how the encoder should encode a dictionary. 
The following change makes the encoder produce key-value pairs. One caveat is that decoding is challenging when the keys are not known. However, this is not required for events as far as I understand.
=> Encode EncodeableDictionary as dictionary

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
Added "Time" and "ReceiveTime" as default select clauses (if not already added) so that SourceTimestamp and ServerTimestamp can be set. Corrected a bug in GetFieldDisplayName when trying to access a display name outside the template array.
=> Add event timestamp fields

e2e-tests/IIoTPlatform-E2E-Tests/Discovery/DiscoveryTestContext.cs, e2e-tests/IIoTPlatform-E2E-Tests/Discovery/DiscoveryTestTheory.cs, e2e-tests/IIoTPlatform-E2E-Tests/Orchestrated/A_PublishSingleNodeOrchestratedTestTheory.cs, e2e-tests/IIoTPlatform-E2E-Tests/Orchestrated/B_PublishMultipleNodesOrchestratedTestTheory.cs, e2e-tests/IIoTPlatform-E2E-Tests/TestExtensions/IIoTPlatformTestContext.cs, e2e-tests/IIoTPlatform-E2E-Tests/TestHelper.Discovery.cs, e2e-tests/IIoTPlatform-E2E-Tests/TestHelper.Registry.cs, e2e-tests/IIoTPlatform-E2E-Tests/TestHelper.cs, e2e-tests/IIoTPlatform-E2E-Tests/Twin/TwinTestContext.cs, tools/e2etesting/DeployPLCs.ps1, tools/e2etesting/pipeline_orchestrated.yml
Switch to using IP addresses of the test servers so that we can use the same tests for servers that have only private IP (for example for the nested edge validation)
=> Use IP address of the test servers instead of fqdn

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
Call to ConditionRefresh was in a slightly wrong place and not wrapped in a try/catch block, causing intermittent null reference exceptions
=> Moved the call to ConditionRefresh

e2e-tests/IIoTPlatform-E2E-Tests/Orchestrated/A_PublishSingleNodeOrchestratedTestTheory.cs, e2e-tests/IIoTPlatform-E2E-Tests/Orchestrated/B_PublishMultipleNodesOrchestratedTestTheory.cs, e2e-tests/IIoTPlatform-E2E-Tests/TestHelper.Discovery.cs
This is the first step of the E2E refactoring, to remove the duplicated code. Later I would like to get away from using this many static helper methods and replace them with something simpler and more understandable.
=> Refactoring: Use the helper method for REST calls

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/LegacyJobOrchestrator.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/NetworkMessageEncoder.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Storage/PublishedNodesJobConverter.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/tests/Engine/LegacyJobOrchestratorTests.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/tests/Engine/pn_assets.json, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/tests/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Tests.csproj, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/tests/Storage/PublishedNodesJobConverterTests.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/PubSub/NetworkMessage.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Core/Extensions/ConnectionModelEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Core/Models/ConnectionModel.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/NodeIdModel.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/OpcAuthenticationMode.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/OpcNodeModel.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/PublishedItemModel.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/PublishedNodesEntryModel.cs, modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Runtime/LegacyCliOptions.cs
merge fix [published nodes with different "groups/assets" for same endpoint causing closing and reopening of sessions #1017](https://github.com/Azure/Industrial-IoT/pull/1017).
This requires also merge of:
aad90ac[](https://github.com/Azure/Industrial-IoT/commit/aad90ac0be31a8ba0b2f416874c85d237e1e1a27)
72bede2[](https://github.com/Azure/Industrial-IoT/commit/72bede29649073e53c7d38ab7d44c0ea6a1eff16)
3c96d7a[](https://github.com/Azure/Industrial-IoT/commit/3c96d7afd1cc05d90f7e9689630a9b7c5b6b3724)
=> merge fix published nodes with different "groups/assets" for same endpoint causing closing and reopening of sessions #1017

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Encoders/Models/EncodeableDictionary.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/tests/Stack/Encoders/Models/EncodeableDictionaryTests.cs
Do not write key-value pairs with an empty key. Added test to check as well. Generalized the `KeyCount` parameter as well to `Count`. More interpretable in the output.
=> Prevent empty key-value pairs in EncodeableDictionary

services/src/Microsoft.Azure.IIoT.Services.OpcUa.Twin.History/src/Startup.cs
The unit tests were passing because the dependency was added as a test dependency.  It should be the dependency of the overall service.  Addresses #1137 as per already provided suggestion in the bug.
=> Adding missing variant encoder factory dependency.

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Extensions/NodeIdEx.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/tests/Stack/Extensions/NodeIdExTests.cs
* do not change OPC UA namespace URI after parsing it.
* added to to show uri.NoQueryAndFragment().AbsoluteUri behavior parsing http://contosos.com
* formatting and make tests pass
Co-authored-by: Martin Regen <mregen@microsoft.com>
Co-authored-by: Dovydas Jarukaitis <dovydas.jarukaitis@tinkamaskodas.lt>
=> do not change OPC UA namespace URI after parsing it. (#738)

tools/e2etesting/ReplaceVariablesInAppSettings.ps1, tools/e2etesting/pipeline_orchestrated.yml, tools/e2etesting/pipeline_standalone.yml, tools/e2etesting/steps/deployplatform.yml, tools/scripts/acr-build.ps1, tools/scripts/set-version.ps1, tools/templates/acrbuild.yml, version.json
This PR does the following
1. Enables Continuous Integration, Continuous Deployment by enabling
following
- PR Build Completion Triggers Orchestrated Pipeline E2E test (Aka CD follows CI)
- Adds Code Coverage to PR Pipeline as required step (Adds PR Gate)
- Uses Key vault to retrieve secrets like username, password by default if unspecified for CD
- Uses default branch "main" for pointing to a 'ImageNameSpace' if unspecified for CD
- Uses default version i.e. last successfully built version from
last commit on the main branch to run end to end test if
unspecified (CI build default)
- PR builds are generated in 'Industrailiotdev' container registry by default and 'main' is the default ImageNameSpace for 
building (CI/PR gates)
- Run scheduled nightly builds on both CI Pipeline (PR …
=> Enable CI/CD for main branch

e2e-tests/IIoTPlatform-E2E-Tests/deploy/IoTHubEdgeBaseDeployment.cs, tools/e2etesting/pipeline_orchestrated.yml, tools/e2etesting/pipeline_standalone.yml, tools/e2etesting/steps/runtests.yml
Changes:
* Added loading of container registry details from Key Vault for standalone pipeline.
* We should always consume `edgeAgent` and `edgeHub` from `mcr.microsoft.com`.
=> Enabling nightly builds for Standalone E2E pipeline.

deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/AksMgmtClient.cs
Changes:
* Changed logic of latest Kubernetes version selection.
* Upgraded default AKS version to `1.18.17`.
The main change here is that now we select higher version between latest returned patch version from SDK and `AksMgmtClient.KUBERNETES_VERSION_FALLBACK`. This is required as the call that we perform through SDK no longer returns latest version that is available. At the moment there is a discrepancy between returned versions through SDK and Azure CLI. I've filed a bug for this in the GitHub repository of C# SDK. Please check it for more context on this fix. When the returned list in SDK is fixed, the changed logic should still choose the correct version.
Bug in C# SDK: [[BUG] Discrepancy in available Kubernetes versions (AKS) returned from Azure CLI and C# SDK …
=> IAI: Changed logic of latest Kubernetes version selection.

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
Removed the DataValue wrapper for each EncodeableDictionary and explicitly set the type to ExtensionObject[] for the encoder to behave as intended.
=> Fix encoding of pending alarms

tools/e2etesting/pipeline_orchestrated.yml, tools/e2etesting/pipeline_standalone.yml, tools/e2etesting/steps/deployplatform.yml, tools/e2etesting/steps/variables.yml, version.json
This PR does the following 
* Adds a new key vault for fetching secrets for staging releases
* Identifies branch as 'release' and updates the ImageNamespace to "public"
* Enables nightly scheduled runs for 'release' branch
=> Enable CI/CD for release branch

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
Feature that (asynchronously) checks whether the types referenced in the where clause is valid types - and writes a warning if it isn't.
=> Check where clause 

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Encoders/Models/EncodeableDictionary.cs
Allow LocalizedText without Locale (only Text) to be encoded. For example, generated by OPC-PLC.
=> Fix filtering of LocalizedText in EncodeableDictionary

docs/opc-event-configuration.md
The example was missing an object in the example JSON. Standardized the indentation also.
=> Fix example JSON (missing object)

deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Microsoft.Azure.IIoT.Deployment.csproj, deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/ArmTemplates.Designer.cs, deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/ArmTemplates.resx, deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/deployments/jumpbox-vm-setup.json, deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/deployments/jumpbox-vm.json
Changes:
* `jumpbox-vm.json` ARM template has been split into two: the first one (`jumpbox-vm.json`) performs deployment of Azure resources and the second one (`jumpbox-vm-setup.json`) performs installation of Helm charts from the jumbox VM.
* Introduced a delay of one minute between deployments of those two ARM templates to allow for role assignments to be applied.
=> IAI: Introduced a delay before Helm chart installation to allow for role assignments to be applied.

components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Encoders/Models/EncodeableDictionary.cs, components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/tests/Stack/Encoders/Models/EncodeableDictionaryTests.cs, modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/tests/ReversibleEncodingIntegrationTests.cs
By taking a dependency on the JsonDecoderEx, which can decode a dictionary, we no longer need to encode Count and Keys separately.
=> Remove encoded Keys and Count from EncodeableDictionary
