Azure/Industrial-IoT

- common/src/Microsoft.Azure.IIoT.Core/src/Extensions/UriEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge/src/Publisher/Servers/PublisherDiscovery.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge/src/Supervisor/SupervisorServices.cs
- modules/opc-twin/src/Runtime/Config.cs
* fixed the connection string for endpoints twin management using the Iot EdgeHub 
* fixed the unix socket based (unix://..) edgelet communication on windows
> [opctwin] - fixes to  run as windows edge-module

- services/deploy/deploy.ps1
- services/deploy/local/template.json
For deployment type "vm" and "local", automatically select tenantId from the subscription.
> deployment fixes

- common/src/Microsoft.Azure.IIoT.Core/src/Extensions/ObjectEx.cs
- common/src/Microsoft.Azure.IIoT.Core/src/Messaging/Default/EventBusHost.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Encoders/JsonEncoderEx.cs
* Fix encoder to throw better exceptions so we can debug unit tests.
* Better value rank checking to comply with OPC UA rank definitions.
* Fix exception when exiting due to changing handler array while enumerating.
> Fixes for encoder and enumerator error

- docs/architecture.md
My first PR to our repo. :)
This is to fix a minor doc issue and verify my dev environment.
> Fix issue https://github.com/Azure/Industrial-IoT/issues/75

- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/AuthorizationMgmtClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Microsoft.Azure.IIoT.Deployment.csproj
Refactoring of role assignment retry logic.
Updated NuGet packages of Microsoft.Azure.IIoT.Deployment
> IAI: Minor refactoring of role assignment retry logic.

- deploy/src/Microsoft.Azure.IIoT.Deployment/DeploymentExecutor.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/AzureResourceManager.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/CosmosDBMgmtClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/EventHubMgmtClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/IotHubMgmtClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/KeyVaultMgmtClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/ServiceBusMgmtClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/SignalRMgmtClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/StorageMgmtClient.cs
* Ignoring name availability check errors.
* Minimizing logs when name availability APIs are not available.
> IAI: Ignoring name availability check errors and using generated names instead.

- docs/industrial_iot_deployment.md
* Added notes about run modes.
* Removed AKS connectivity parts from Missing Features.
* Updated Sample Run section.
* Added list of configuration parameters.
> Feature/iai/docs: Changed IAI docs to reflect current state of code.

- deploy/src/Microsoft.Azure.IIoT.Deployment/IIoTK8SClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/IIoTDeploymentTags.Designer.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/IIoTDeploymentTags.resx
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/IIoTK8SResources.Designer.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/00_industrial_iot_namespace.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/01_industrial_iot_serviceaccount.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/02_industrial_iot_role.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/03_industrial_iot_role_binding.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/10_industrial_iot_env_secret.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/11_registry_deployment.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/11_registry_service.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/12_twin_deployment.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/12_twin_service.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/13_history_deployment.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/13_history_service.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/14_gateway_deployment.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/14_gateway_service.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/15_vault_deployment.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/15_vault_service.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/16_alerting_deployment.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/17_onboarding_deployment.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/18_jobs_deployment.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/19_modelprocessor_deployment.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/20_blobnotification_deployment.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/21_twinwebui_deployment.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/25_default_ssl_certificate_secret.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/30_industrial_iot_ingress.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/appsettings.json
- docs/industrial_iot_deployment.md
* Changed version of deployed services from 2.5.1 to 2.5.2.
* Increased ingress IP Address creation timeout to 10 minutes.
* Removed mention of known issues about CosmosDB
> Feature/iai/2.5.2: Upgraded version of micro-services to 2.5.2

- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Applications.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Browser.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Discoverers.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Endpoints.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Services/Registry.cs
- samples/src/Microsoft.Azure.IIoT.App/src/Shared/NavMenu.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Startup.cs
remove setting link
fix Browse and Assets navigation
replace old Api with new query Api
> logout return to main page

- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Applications.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Browser.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Discoverers.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Endpoints.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Gateways.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Index.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Publishers.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Services/Browser.cs
- samples/src/Microsoft.Azure.IIoT.App/src/Services/Registry.cs
- samples/src/Microsoft.Azure.IIoT.App/src/Shared/MainLayout.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Shared/NavMenu.razor
- samples/src/Microsoft.Azure.IIoT.App/src/wwwroot/css/site.css
- samples/src/Microsoft.Azure.IIoT.App/src/wwwroot/css/spinner.css
add spinner when loading data
optimized read value when browsing
fix scan status
'about' button redirect to github Industrial-Iot page
> getting data after page rendering

- azure-pipelines-simulation.yml
- azure-pipelines.yml
- tools/scripts/acr-build.ps1
- tools/templates/acrbuild.yml
> Container builds with better traces and parallel to nuget/deploy exe

- common/src/Microsoft.Azure.IIoT.Abstractions/src/PcsVariable.cs
- common/src/Microsoft.Azure.IIoT.AspNetCore/src/Auth/Extensions/DataProtectionBuilderEx.cs
- common/src/Microsoft.Azure.IIoT.Core/src/Crypto/KeyVault/Runtime/KeyVaultConfig.cs
- common/src/Microsoft.Azure.IIoT.Core/src/Hub/Runtime/IoTHubEventConfig.cs
Added the following environment variables:
- `PCS_STORAGE_CONTAINER_DATAPROTECTION`
- `PCS_KEYVAULT_KEY_DATAPROTECTION`
> Made data protection parameters configurable.

- common/src/Microsoft.Azure.IIoT.Abstractions/src/PcsVariable.cs
- common/src/Microsoft.Azure.IIoT.Core/src/Cdm/ICdmClientConfig.cs
- common/src/Microsoft.Azure.IIoT.Core/src/Cdm/Runtime/CdmClientConfig.cs
- common/src/Microsoft.Azure.IIoT.Core/src/Messaging/SignalR/Runtime/SignalRServiceConfig.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Cdm/src/Services/CdmMessageProcessor.cs
- services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry.Cdm/src/Runtime/Config.cs
Added the following variables to `PcsVariable.cs`:
* `PCS_ADLSG2_CONNSTRING`
* `PCS_ADLSG2_CONTAINER_CDM`
* `PCS_ADLSG2_CONTAINER_CDM_ROOTFOLDER`
* `PCS_SIGNALR_HUBNAME`
Renamed `ADLSg2BlobName` parameter to `ADLSg2ContainerName `.
> feature/cdm_config: minor changes to CDM configuration.

- deploy/scripts/deploy.ps1
- docs/deploy/howto-deploy-all-in-one.md
* Wording
* Error indication
* Resource group as application name bug when alpha num test fails
* Start browser if possible for $website
> Fix several bugs in deploy script

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Publisher/src/Clients/v2/PublisherJobClient.cs
- modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/v2/Controller/ConfigurationSettingsController.cs
default the SiteId to DeviceId in case  is not specified for publisher capabilities
> Default SiteId for Publisher

- deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/IIoTK8SClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/CosmosDBMgmtClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/EventHubMgmtClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Microsoft.Azure.IIoT.Deployment.csproj
Product Backlog Item: [#6046942](https://msazure.visualstudio.com/One/_workitems/edit/6046942)
* Upgraded Event Hub Namespace to Standard tier.
* Upgraded Microsoft.Graph.Auth NuGet package.
* Increased Ingress creation timeout to 15 minutes.
* Upgraded NuGet packages.
> IAI: Upgraded Event Hub Namespace to Standard tier.

- deploy/scripts/aad-register.ps1
- deploy/scripts/deploy.ps1
Bugs:
* https://github.com/Azure/Industrial-IoT/issues/312
* https://github.com/Azure/Industrial-IoT/issues/217
> Bugfix: Connect-AzureAD falls back to login without account details.

- deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/EventHubMgmtClient.cs
Creating the following consumer groups for Event Hub:
- `telemetry_cdm`
- `telemetry_ux`
> IAI: Event Hub: Creating necessary consumer groups.

- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/AzureResourceManager.cs
UKSouth is commented out as there is no capacity at the moment to test it.
> IAI: Added several more regions.

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Extensions/ServiceResultEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/ClientSession.cs
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Endpoints.razor
Fix session connect handling to peek the next operation.  Allow browsing unauthorized endpoints.
> Fix kepware auth when anonymous login is not enabled

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Discovery/src/Services/DiscoveryServices.cs
- samples/src/Microsoft.Azure.IIoT.App/src/Services/Registry.cs
Also add loopback/localhost to found addresses for port scanning to support scanning windows hosts.
> Fix performance in UI by removing individual reads

- docs/deploy/quickstart-gateway-installer.md
Added the steps to clarify how to install the Edge gateway and industrial IoT components on Linux
> gateway installation steps for Linux

- common/src/Microsoft.Azure.IIoT.Hub.Module.Framework/src/Hosting/SettingsRouter.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Cdm/src/Services/CdmMessageProcessor.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Cdm/src/Storage/AdlsCsvStorage.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/LegacyJobOrchestrator.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/MonitoredItemMessageEncoder.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/NetworkMessageEncoder.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Storage/PublishedNodesJobConverter.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Extensions/StackTypesEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/PubSub/MonitoredItemMessage.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/PubSub/MonitoredItemMessageContentMask.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Subscriber/src/Handlers/MonitoredItemSampleBinaryHandler.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Subscriber/src/Handlers/MonitoredItemSampleJsonHandler.cs
* standalone supports up to 5 sessions
* sequence number added to the message
* fixes for CDM handling
> various fixes for publisher

- lgtm.yml
Currently on Javascript works, fix C# -->
https://lgtm.com/projects/g/Azure/Industrial-IoT/?mode=list
> Enable lgtm build

- samples/src/Microsoft.Azure.IIoT.App/src/Models/ListNode.cs
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Browser.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Endpoints.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/_DrawerPublisherContent.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Services/Publisher.cs
fix deactivate checkbox
shorten security profile in endpoint page
> add publisher config

- .editorconfig
> Add final newline to .json and .sh files

- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Endpoints.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Startup.cs
> Fix browsing from asset page

- samples/src/Microsoft.Azure.IIoT.App/src/Properties/launchSettings.json
It's not needed for writing exceptions in the console
> Development env removed

- deploy/templates/azuredeploy.platform.json
- readme.md
Change app service plan from B3 to B1
> Enabling client Affinity cookie to fix webSockets error

- common/src/Microsoft.Azure.IIoT.Abstractions/src/PcsVariable.cs
- common/src/Microsoft.Azure.IIoT.Auth.ActiveDirectory/src/Extensions/ConfigurationEx.cs
- deploy/helm/azure-industrial-iot/README.md
- deploy/helm/azure-industrial-iot/templates/10_industrial_iot_env_secret.yaml
- deploy/helm/azure-industrial-iot/values.yaml
Bug: [[BugBash] KeyVault configuration should be optional.](https://msazure.visualstudio.com/One/_workitems/edit/7288166)
> Making KeyVault configuration provider optional.

- samples/src/Microsoft.Azure.IIoT.App/src/Components/Pager/Pager.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Extensions/PageResultEx.cs
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Endpoints.razor
- Visually show which page the user is currently on 
- Write the asset url 
- Fix the button visualization
> Frontend fixes

- common/src/Microsoft.Azure.IIoT.Core/src/Hub/Services/IoTHubEdgeBaseDeployment.cs
- Enable upload and read logs of edge modules
- Enable metrics collection of Edge Hub and Edge Agent
> enabling logging for edge modules

- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/deployments/jumpbox-vm.json
- deploy/templates/azuredeploy.json
- deploy/templates/azuredeploy.standard.json
* PS1: Fixing TSI tags.
* PS1: Removed Storage Blob Data Contributor role assignment.
* Minor typo in jumpbox-vm.json.
> Minor improvements of deployment ARM templates.

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Encoders/JsonDecoderEx.cs
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Browser.razor.cs
- samples/src/Microsoft.Azure.IIoT.App/src/Services/Publisher.cs
* fixed the json decoding of ulong values
* removed DisplayName setting in the engineering tool since the publisher is reading this from the server
> small fixes

- common/src/Microsoft.Azure.IIoT.Diagnostics.AppInsights/src/Extensions/ContainerBuilderEx.cs
- services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry.Sync/src/Program.cs
- services/src/Microsoft.Azure.IIoT.Services.Processor.Events/src/Program.cs
- services/src/Microsoft.Azure.IIoT.Services.Processor.Onboarding/src/Program.cs
- services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry.Cdm/src/Program.cs
- services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry/src/Program.cs
- services/src/Microsoft.Azure.IIoT.Services.Processor.Tunnel/src/Program.cs
Using: [Application Insights for .NET console applications](https://docs.microsoft.com/azure/azure-monitor/app/console)
* Added Application Insights dependency tracking.
* Added AddDependencyTracking() to .NET Core apps.
> Added Application Insights dependency tracking for .NET Core apps.

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/DataFlowProcessingEngine.cs
* Add avg (billed) IoT Hub chunks
* Add estimated messages per day
* Refactor/reformat diagnostic info code
> Enhancements for diagnostic info

- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Applications.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Browser.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Discoverers.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Endpoints.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Gateways.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/PublishedNodes.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Publishers.razor
- samples/src/Microsoft.Azure.IIoT.App/src/Pages/Supervisors.razor
* Add class table-responsive: https://getbootstrap.com/docs/4.5/content/tables/
* Can scroll horizontally using touch on mobile devices
> Make Blazor tables responsive

- deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/AksMgmtClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/OperationalInsightsMgmtClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/SignalRMgmtClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Microsoft.Azure.IIoT.Deployment.csproj
- docs/deploy/howto-deploy-aks.md
* Upgraded Kubernetes version from `1.15.7` to `1.16.9`.
* Upgraded `Microsoft.Azure.Management.*` NuGet packages.
* Upgraded `Microsoft.Graph.*` NuGet packages.
* Upgraded `KubernetesClient` NuGet package to `2.0.26`.
* Updated Kubernetes dashboard documentation.
> IAI: Upgraded Kubernetes version to 1.16.9.

- deploy/helm/azure-industrial-iot/Chart.yaml
- deploy/helm/azure-industrial-iot/README.md
- deploy/helm/azure-industrial-iot/templates/10_industrial_iot_env_secret.yaml
- deploy/helm/azure-industrial-iot/values.yaml
- Helm: Upgrading chart to version `0.3.1`, appVersion `2.7.170`.
- Helm: Removed SignalR from list of required Azure resources.
> Helm: Upgrading chart to version 0.3.1, appVersion 2.7.170.

- deploy/helm/azure-industrial-iot/Chart.yaml
- deploy/helm/azure-industrial-iot/README.md
- deploy/helm/azure-industrial-iot/values.yaml
- docs/deploy/howto-add-aks-to-ps1.md
- docs/deploy/howto-deploy-helm.md
* Helm: Bumped chart version to `0.4.0` and appVersion to `2.8.2` as `0.3.1` version of the chart is already released.
* Helm: Updated deployment docs.
> Helm: Bumped chart version to 0.4.0 and appVersion to 2.8.2.

- readme.md
* Fix getting started doc links
> Fix broken links due to backslash

- Industrial-IoT.sln
- common/src/Microsoft.Azure.IIoT.Core/src/Tasks/LimitingScheduler.cs
- common/src/Microsoft.Azure.IIoT.Core/src/Tasks/ThreadPerTaskScheduler.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/DataFlowProcessingEngine.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/IoTHubMessageSink.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/MonitoredItemMessageEncoder.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/NetworkMessageEncoder.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/WriterGroupMessageSource.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/IMessageEncoder.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/IMessageTrigger.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Models/MonitoredItemNotificationModel.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Publisher/src/Services/PublisherJobService.cs
- modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Runtime/LegacyCliOptions.cs
- platform/publisher/Microsoft.Azure.IIoT.Platform.Publisher.Edge/cli/Microsoft.Azure.IIoT.Platform.Publisher.Edge.Cli.csproj
- platform/publisher/Microsoft.Azure.IIoT.Platform.Publisher.Edge/cli/Program.cs
- platform/publisher/Microsoft.Azure.IIoT.Platform.Publisher.Edge/cli/Properties/launchSettings.json
* new test harness for long running testing
* New json encoding
* Bounding and optimization of flow.
> Performance optimizations and long running tests for publisher 2.7.17x

- deploy/scripts/deploy.ps1
- docs/deploy/howto-deploy-all-in-one.md
* Add doc for tenant param
* Remove unused param accountName
* Fix wordings
* Update doc with params from ps1 file
> Update deploy.ps1 params

- docs/deploy/howto-deploy-all-in-one.md
<application-name> should be instead of <name> otherwise if a they are different then the return url will not be set correctly
> Remove source of confusion

- deploy.cmd
> Fix deploy.cmd with -version param

- docs/tutorials/azuredeploy.aci.simulation.json
* Using "admin" causes deployment to fail
> Change default username in cost estimation ARM template

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/DataFlowProcessingEngine.cs
> Increase payload buffer for PubSub header to 2 KB

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/DataFlowProcessingEngine.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/DefaultSessionManager.cs
* Closes #657 
* Remove unnecessary checks from diag info
> Fix sporadic InvalidOperationException when reconnecting to network

- api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Models/DataSetWriterApiModel.cs
- api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Models/WriterGroupApiModel.cs
- common/src/Microsoft.Azure.IIoT.Core/src/Hub/Services/IoTHubDeviceEventHandler.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Cdm/src/Services/CdmMessageProcessor.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/NetworkMessageEncoder.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/WriterGroupJobModel.cs
- docs/code-structure.md
- docs/dev-guides/telemetry-messages-format.md
- docs/industrial-iot-components.md
- docs/services/events.md
- docs/services/processor-telemetry.md
- docs/services/publisher.md
- docs/tutorials/readme.md
- docs/tutorials/tut-timeseriesinsights.md
- services/src/Microsoft.Azure.IIoT.Services.OpcUa.Events/src/Startup.cs
- services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry/src/Program.cs
Replaced references of Pub/Sub with PubSub as per official naming.
> Replaced references of Pub/Sub with PubSub as per official naming.

- common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Storage/Database/Services/JobDatabase.cs
- common/src/Microsoft.Azure.IIoT.Core/src/Storage/CosmosDb/Runtime/CosmosDbConfig.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Publisher/src/Services/PublisherJobService.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Configuration/ConsoleConfigurationProvider.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/AksMgmtClient.cs
Bug: [[IAI] Specifying existing resource group during deployment not working.](https://msazure.visualstudio.com/One/_workitems/edit/8119388)
Changes:
* IAI: Added notes to selection prompts to use index.
* Minor formatting in PublisherJobService.cs.
* Minor formatting changes in JobDatabase and CosmosDbConfig.
* Minor formatting changes in AksMgmtClient.cs.
> IAI: Added notes to selection prompts to use index.

- common/src/Microsoft.Azure.IIoT.Core/src/Diagnostics/Extensions/SerilogEx.cs
Adding timestamp in UTC in log template.
> adding date to log entries

- deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/ApplicationsManager.cs
RedirectURIs have been updated from `2.6.x`-specific ones to `2.7.x`-specific ones.
> IAI: Updated RedirectURIs for 2.7.x and latest versions.

- docs/deploy/howto-install-iot-edge.md
* Fix JSON syntax
* Wording improvements
> Reformat layered deployment section

- tools/scripts/acr-release.ps1
- tools/scripts/docker-build.ps1
- tools/scripts/docker-source.ps1
from list: https://hub.docker.com/_/microsoft-windows-nanoserver
> Use latest amd64 docker base images (#721)

- docs/deploy/howto-run-microservices-locally.md
Fix error for the hyper-link of "Authenticating to Key vault"
> Fix link for "Authenticating to Key vault"

- docs/deploy/howto-deploy-all-in-one.md
- docs/deploy/howto-register-aad-applications.md
Changes:
* Added App Registration pre-creation steps using `deploy.ps1` and `aad-register.ps1`.
* Added App Registration pre-creation steps using `Microsoft.Azure.IIoT.Deployment`.
* Removed language references from links in `howto-deploy-all-in-one.md`. Minor formatting changes.
> Added steps for App Registration pre-creation using existing deployment tools.

- common/src/Microsoft.Azure.IIoT.Abstractions/src/IoTEdgeVariables.cs
- common/src/Microsoft.Azure.IIoT.Hub.Module.Client/src/Default/IoTSdkFactory.cs
- common/src/Microsoft.Azure.IIoT.Hub.Module.Framework/src/Clients/EdgeletClient.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Extensions/ModuleConfigEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Twin/src/Supervisor/Services/SupervisorServices.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs
Changes:
* Collected IoT Edge environment variables in `IoTEdgeVariables` class.
* Fixing a typo.
> Collected IoT Edge environment variables in IoTEdgeVariables class.

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Migration/VaultApplicationMigration.cs
Removing `AppsAndCertRequests` CosmosDB container after migration of Application entities from there.
> Removing AppsAndCertRequests CosmosDB container after migration.

- tools/e2etesting/DeployTestEventProcessor.ps1
- tools/e2etesting/pipeline.yml
Added support to automatically reuse testing resources
> Add support to reuse test resources

- e2e-tests/IIoTPlatform-E2E-Tests/TestConstants.cs
- tools/e2etesting/DeployTestEventProcessor.ps1
- tools/e2etesting/pipeline.yml
Added missing environment variable that needs to be passed to xUnit.
> Added missing environment variable

- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/deployments/jumpbox-vm.json
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/scripts/jumpbox.sh
Changes:
- Upgraded Ubuntu version on jumpbox to `18.04-LTS`.
- Upgraded Helm client version on jumpbox to `3.3.4`.
> IAI: Upgraded Ubuntu version on jumpbox to 18.04-LTS.

- tools/e2etesting/ReplaceVariablesInAppSettings.ps1
- tools/e2etesting/appSettings.json
- tools/e2etesting/pipeline.yml
Added propagation of `PlatformVersion` pipeline variable to:
- `appSettings.json` file for IAI, as `Helm:ImageTag`
- tests via `PCS_IMAGES_TAG` environment variable
> Added propagation of platform version to IAI and tests.

- deploy/src/Microsoft.Azure.IIoT.Deployment/Configuration/Extensions/RegionTypeExtension.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Configuration/RegionType.cs
Applying changes by @markusstuhler in #935 on `master`.
> IAI: Added support of cmd-style region names.

- deploy/src/Microsoft.Azure.IIoT.Deployment/Authentication/AuthenticationManagerFactory.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Authentication/ClientCredentialsAuthenticationManager.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Authentication/CodeFlowAuthenticationManager.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Authentication/IAuthenticationManager.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Authentication/InteractiveAuthenticationManager.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/IIoTK8SResources.Designer.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/Scripts.Designer.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/aks/90_letsencrypt_cluster_issuer.yaml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/scripts/jumpbox.sh
- docs/deploy/howto-add-aks-to-ps1.md
- docs/deploy/howto-deploy-aks.md
Changes:
* Upgraded `cert-manager` Helm chart to version `1.1.0`.
* Added some code documentation.
* Upgraded `ingress-nginx` Helm chart to version `3.12.0`.
* Enabled default backend for `ingress-nginx`.
* Updated documentation of `Microsoft.Azure.IIoT.Deployment`.
* Updated documentation of adding an AKS cluster.
> IAI: Upgraded cert-manager and ingress-nginx charts.

- e2e-tests/IIoTPlatform-E2E-Tests/IIoTPlatform-E2E-Tests.csproj
- e2e-tests/IIoTPlatform-E2E-Tests/Standalone/PublishNodesFromFileTestTheory.cs
- e2e-tests/IIoTPlatform-E2E-Tests/TestConstants.cs
- e2e-tests/IIoTPlatform-E2E-Tests/TestExtensions/IIoTPlatformTestContext.cs
- e2e-tests/IIoTPlatform-E2E-Tests/TestHelper.cs
- e2e-tests/IIoTPlatform-E2E-Tests/deploy/IoTHubPublisherDeployment.cs
start adding test for standalone publisher
> fix helper methods for standalone test

- e2e-tests/IIoTPlatform-E2E-Tests/Orchestrated/PublishSingleNodesTestTheory.cs
- e2e-tests/IIoTPlatform-E2E-Tests/RegistryHelper.cs
- e2e-tests/IIoTPlatform-E2E-Tests/Standalone/PublishNodesFromFileTestTheory.cs
- e2e-tests/IIoTPlatform-E2E-Tests/TestExtensions/IIoTPlatformTestContext.cs
- e2e-tests/IIoTPlatform-E2E-Tests/TestExtensions/IIoTStandaloneTestCollection.cs
- e2e-tests/IIoTPlatform-E2E-Tests/TestExtensions/IIoTStandaloneTestContext.cs
- e2e-tests/IIoTPlatform-E2E-Tests/deploy/DeploymentConfiguration.cs
- e2e-tests/IIoTPlatform-E2E-Tests/deploy/IoTHubPublisherDeployment.cs
Changes:
* Fixed default image tag.
* Moved deployments to `PublishNodesFromFileTestTheory`.
* Moved `CreateOrUpdateConfigurationAsync` to `RegistryHelper`.
> Refactoring of automated tests.

- tools/scripts/acr-copy-release.ps1
TESTED=created new ACR industrialiotprod, ran the script locally and verified images are getting copied. I had to add --force flag to acr import command in order to override "latest" tag.
> New release script to copy build images to prod ACR

- deploy/src/Microsoft.Azure.IIoT.Deployment/Configuration/HelmSettings.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/deployments/jumpbox-vm.json
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/scripts/jumpbox.sh
- deploy/src/Microsoft.Azure.IIoT.Deployment/appsettings.json
- tools/e2etesting/ReplaceVariablesInAppSettings.ps1
- tools/e2etesting/appSettings.json
- tools/e2etesting/steps/deployplatform.yml
- Support for private container registry in IAI
- Add new properties to HelmSettings
- Update parameters to jumpbox-vm
- Update parameters to extension scripts for jumpbox-vm
- If private repo: create k8 secret, update helm install command, pass private repo credentials to microservices for layered deployment
- Test the setup in e2etesting for orchestrated mode
> Enable E2E pipeline for internal ACR

- e2e-tests/IIoTPlatform-E2E-Tests/Orchestrated/C_DiscoverEndpointsTestTheory.cs
- e2e-tests/IIoTPlatform-E2E-Tests/TestConstants.cs
Discoverer tests:
1) Find a server on a specific ip address
2) Find servers using the port range
3) Find all registered applications
> Discoverer e2e tests

- api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Extensions/ModelExtensions.cs
- api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Models/PublishedDataSetEventApiModel.cs
- api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Models/PublishedDataSetSourceApiModel.cs
- api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Models/PublishedEventItemsApiModel.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Extensions/PublishedDataItemsModelEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Extensions/PublishedDataSetEventsModelEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Extensions/PublishedDataSetSourceModelEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Extensions/PublishedEventItemsModelEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Extensions/PublishedDataSetEventsDataModelEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Extensions/PublishedEventItemsModelEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/PublishedDataSetEventModel.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/PublishedDataSetSourceModel.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/PublishedEventItemsModel.cs
Preparatory work for making events work in OpcPublisher. This PR is fixing some inconsistencies in the published data set models, where events was not properly defined. This PR is one of four needed to implement events.
> Refactored data set models

- docs/tutorials/azuredeploy.aci.simulation.json
- docs/tutorials/tut-iiot-cost-estimation.md
* Update ARM template for cost estimation
* Marketplace Ubuntu image with IoT Edge has been deprecated, replace with stock and up-to-date Ubuntu 18.04 image
* Install iotedge using [this customData](https://raw.githubusercontent.com/Azure/iotedge-vm-deploy/master/edgeDeploy.json)
* Update OPC-PLC to 1.2.2
> Use Ubuntu 18.04 in cost estimation ARM template

- e2e-tests/IIoTPlatform-E2E-Tests/Orchestrated/C_DiscoverEndpointsTestTheory.cs
- e2e-tests/IIoTPlatform-E2E-Tests/TestExtensions/IIoTPlatformTestContext.cs
- e2e-tests/IIoTPlatform-E2E-Tests/TestHelper.cs
- e2e-tests/IIoTPlatform-E2E-Tests/Twin/TwinCallTestTheory.cs
- fetch metadata test
- call method test
- endpoint certificate test
> Twin call method and method metadata tests 

- e2e-tests/IIoTPlatform-E2E-Tests/TestHelper.Twin.cs
- e2e-tests/IIoTPlatform-E2E-Tests/Twin/TwinBrowseTestTheory.cs
- e2e-tests/IIoTPlatform-E2E-Tests/Twin/TwinCallTestTheory.cs
- e2e-tests/IIoTPlatform-E2E-Tests/Twin/TwinReadNodeValueTestTheory.cs
- e2e-tests/IIoTPlatform-E2E-Tests/Twin/TwinReadTestTheory.cs
- e2e-tests/IIoTPlatform-E2E-Tests/Twin/TwinTestContext.cs
- e2e-tests/IIoTPlatform-E2E-Tests/Twin/TwinWriteNodeValueTestTheory.cs
- e2e-tests/IIoTPlatform-E2E-Tests/Twin/TwinWriteTestTheory.cs
add twin tests for read and write node value
> e2e twin test read and write node

- api/src/Microsoft.Azure.IIoT.Api/src/History/Extensions/ModelExtensions.cs
- api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Extensions/ModelExtensions.cs
- api/src/Microsoft.Azure.IIoT.OpcUa.Api/src/Core/Models/SimpleAttributeOperandApiModel.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/NetworkMessageEncoder.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/tests/Model/MonitoredItemModelTests.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Extensions/MonitoredItemNotificationModelEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Extensions/StackModelsEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Core/Extensions/SimpleAttributeOperandModelEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Core/Models/SimpleAttributeOperandModel.cs
- modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Properties/launchSettings.json
fix: Added DisplayName for SelectClause elements
fix: removed leading '/' in field names
fix: Message header now uses DisplayName property for event node when generating PubSub messages to IotHub
> Opc UA Events, bugfixes

- e2e-tests/IIoTPlatform-E2E-Tests/Config/IContainerRegistryConfig.cs
- e2e-tests/IIoTPlatform-E2E-Tests/Config/IIoTEdgeConfig.cs
- e2e-tests/IIoTPlatform-E2E-Tests/TestConstants.cs
- e2e-tests/IIoTPlatform-E2E-Tests/TestExtensions/IIoTPlatformTestContext.cs
- e2e-tests/IIoTPlatform-E2E-Tests/TestHelper.cs
- e2e-tests/IIoTPlatform-E2E-Tests/deploy/IoTHubEdgeBaseDeployment.cs
- e2e-tests/IIoTPlatform-E2E-Tests/deploy/IoTHubPublisherDeployment.cs
- tools/e2etesting/steps/runtests.yml
- introduce nested edge flag 
- set edge version
- ssh to the edge VM through jumbox
- enable experimental features for edgeHub
- set unique deployment names
> Code changes for manual nested edge test

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
feat: Added call to ConditionRefresh when subscription changes to enable us to get the current state of conditions and alarms
> Added call to ConditionRefresh()

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Extensions/FilterEncoderEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
fix: WhereClause operands can now be specificed with namespace name in addition to namespace index.
> bug: WhereClause with namespace

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/DataFlowProcessingEngine.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/WriterGroupMessageSource.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/IMessageTrigger.cs
Adding event diagnostic counters to console output and Prometheus metrics
> Add event diagnostic counters

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Encoders/Models/EncodeableDictionary.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/tests/Stack/Encoders/Models/EncodeableDictionaryTests.cs
Added reversible encoding to EncodeableDictionary by writing the set of keys. Added tests to the EncodeableDictionary.
> Add reversible encoding to EncodeableDictionary

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
fix: Enhanced how we build the simple filter and added a property FieldNames to the MonitoredItemWrapper class to better customize the field names in pub sub format for events.
> Enhancing get simple filter and field names

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Discovery/src/Services/DiscoveryServices.cs
fix for https://github.com/Azure/Industrial-IoT/issues/743
* discovery uses how gateway hostname environment variable
* log reports refined
> Fix discovery exception when resolving the gateway's hostname

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
fix; hidden fields now doesn't show up in pubsub json for events
fix: added check so that namespace index isn't out-of-bounds
> Hides hidden fields from json

- common/src/Microsoft.Azure.IIoT.Serializers.NewtonSoft/src/Default/NewtonSoftJsonSerializer.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/LegacyJobOrchestrator.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Storage/PublishedNodesJobConverter.cs
merge commit: [3885ecd](https://github.com/Azure/Industrial-IoT/commit/3885ecd74ddc9379e706086d6704ad42a6744b36)
> Merge bug fix: Dynamic changes to published nodes json file

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/MonitoredItemMessageEncoder.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/WriterGroupMessageSource.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/DefaultSessionManager.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
fix: cleaned up some compiler messages and unused code
> Cleaned up some compiler messages

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/DefaultSessionManager.cs
Cherry picking #679 PR for this bug:
Github issue [link](https://github.com/Azure/Industrial-IoT/issues/669)
> Merge multiple endpoints (#679)

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/tests/Engine/LegacyJobOrchestratorTests.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/tests/Engine/publishednodes.json
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/tests/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher.Tests.csproj
cherry-pick commit 5639f97[](https://github.com/Azure/Industrial-IoT/commit/5639f97e258a09f19a24ae9fd6cbd4028aa149a8)
> Fix multiple endpoints concurrency issue (#716)

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/tests/Storage/PublishedNodesJobConverterTests.cs
Adjusting assertions to properly capture the format. Add tests for simple events filter and pending alarms.
> Fix tests for events in job converter

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Models/LegacyCliModel.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Runtime/Default/SecurityConfig.cs
- modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Runtime/LegacyCliConfigKeys.cs
- modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Runtime/LegacyCliOptions.cs
> Porting #1027 into 2.8 branch 

- modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/ModuleProcess.cs
cherry pick commit c7958d7e[](https://github.com/Azure/Industrial-IoT/pull/978)
> merge add stack trace for publisher (#978)

- modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Runtime/LegacyCliConfigKeys.cs
- modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/Runtime/LegacyCliOptions.cs
Cherry pick [Fails when more 468 values are added to publisher (#850)](https://github.com/Azure/Industrial-IoT/pull/850)
> Merge bug: Fails when more 468 values are added to publisher (#850)

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/ISubscription.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/DefaultSessionManager.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
fix: Added code to send pending alarms message even though the dictionary is empty
> Send pending alarms message even when empty

- common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Agent/Default/Worker.cs
- common/src/Microsoft.Azure.IIoT.Hub.Module.Client/src/Default/IoTSdkFactory.cs
- https://github.com/Azure/Industrial-IoT/pull/780 Cert Store fix
> merge cert store fix (#780)

- azure-pipelines.yml
Enabled CI pipeline execution for pushes to `develop` and `dev/2.8_rc` branches.
> Enabled CI pipeline execution for pushes to develop and dev/2.8_rc branches.

- common/src/Microsoft.Azure.IIoT.Core/src/Hub/Services/IoTHubEdgeBaseDeployment.cs
* set layered deployment edge runtime to 1.1
> set overall iotedge runtime to 1.1 LTS (#1123)

- common/src/Microsoft.Azure.IIoT.Abstractions/src/IoTEdgeVariables.cs
- common/src/Microsoft.Azure.IIoT.Hub.Module.Client/src/Default/IoTSdkFactory.cs
- common/src/Microsoft.Azure.IIoT.Hub.Module.Framework/src/Clients/EdgeletClient.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Discovery/src/Services/DiscoveryServices.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Extensions/ModuleConfigEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Twin/src/Supervisor/Services/SupervisorServices.cs
* discovery using gateway hostname
* add logs for discovery gateway host
> Fix discovery exception when resolving the gateway's hostname (#1125)

- api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Models/DataSetWriterApiModel.cs
- api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Models/WriterGroupApiModel.cs
- common/src/Microsoft.Azure.IIoT.Core/src/Hub/Services/IoTHubDeviceEventHandler.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Cdm/src/Services/CdmMessageProcessor.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/NetworkMessageEncoder.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/WriterGroupJobModel.cs
- docs/code-structure.md
- docs/dev-guides/telemetry-messages-format.md
- docs/industrial-iot-components.md
- docs/services/events.md
- docs/services/processor-telemetry.md
- docs/services/publisher.md
- docs/tutorials/readme.md
- docs/tutorials/tut-timeseriesinsights.md
- services/src/Microsoft.Azure.IIoT.Services.OpcUa.Events/src/Startup.cs
- services/src/Microsoft.Azure.IIoT.Services.Processor.Telemetry/src/Program.cs
Merge commit Extend matching of subscription notification to published nodes #1016 [](1c5525d552dbbd1c0822b02b2daceda4f2ac647a)
This require also merge of commits:
- 6273746d[](6273746d983f9aceb1dffd589b3418c154019917)
- 89120295[](89120295b31a52290c2ae8d085a37e33ad8d2194)
> merge Extend matching of subscription notification to published nodes #1016

- common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Jobs/Hub/JobOrchestratorEndpointSync.cs
- common/src/Microsoft.Azure.IIoT.Core/src/Hub/Auth/Services/TwinIdentityTokenUpdater.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Services/ActivationSyncHost.cs
* Fix for test failures.
* Minor cleanup.
> Fix for test failures. (#906)

- common/src/Microsoft.Azure.IIoT.Diagnostics.AppInsights/src/Default/ApplicationInsightsTelemetryInitializer.cs
- common/src/Microsoft.Azure.IIoT.Diagnostics.AppInsights/src/Microsoft.Azure.IIoT.Diagnostics.AppInsights.csproj
- common/src/Microsoft.Azure.IIoT.Hub.Module.Client/src/Default/IoTSdkFactory.cs
* Undo update to bad ApplicationInsights packages (https://github.com/microsoft/ApplicationInsights-dotnet/issues/2187)
* Fix null reference exception
* Add IoT SDK diagnostics message.
> Fix startup crashes in Application Insights

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
fix: handling refresh required event by calling ConditionRefresh() on the subscription
> Handle RefreshRequiredEventType

- common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Agent/Default/Worker.cs
- common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Agent/Default/WorkerSupervisor.cs
- common/src/Microsoft.Azure.IIoT.Agent.Framework/src/IWorkerSupervisor.cs
- common/src/Microsoft.Azure.IIoT.Agent.Framework/tests/Worker/WorkerSupervisorTests.cs
- #819 Avoid NullReferenceException in case of job continuation
> merge NullReferenceException fix (#819) 

- common/src/Microsoft.Azure.IIoT.Abstractions/src/PcsVariable.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/DataFlowProcessingEngine.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/IEngineConfiguration.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Publisher/src/Services/PublisherJobService.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/EngineConfigurationModel.cs
Ported part of changes present in #671 on `main` branch.
> Increased outgress queue size from 200 to 4096.

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
Refined the ConditionRefresh logging somewhat
> Refined ConditionRefresh logging

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Gateway/src/Server/GatewayServer.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Microsoft.Azure.IIoT.OpcUa.Protocol.csproj
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Encoders/JsonDecoderEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Encoders/JsonEncoderEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Encoders/ModelDecoder.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Encoders/ModelEncoder.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Models/EnumDefinition2.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Nodeset/NodeSet2.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Testing/src/Servers/Reference/ReferenceNodeManager.cs
Work in progress - no need to review this yet
> upgrade opc ua nuget package to  version 1.4.366.31-preview

- tools/e2etesting/DeployPLCs.ps1
Changes to `DeployPLCs.ps1` script:
* Added handling of ACI deployment exceptions. Now an error that occurs in a job to deploy ACIs will be propagated to the main loop of `DeployPLCs.ps1` script and will stop its execution.
* Reduced number of ACIs deployed by default from `18` to `10`.
> Handling ACI deployment exceptions. Reduced number of ACIs to 10.

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
Work in progress: Please hold your reviews
UPDATE: Ready for review
> Made updating and sending pending alarm events thread safe

- deploy/src/Microsoft.Azure.IIoT.Deployment/Configuration/HelmSettings.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/AksMgmtClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Infrastructure/IotHubMgmtClient.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Microsoft.Azure.IIoT.Deployment.csproj
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/deployments/jumpbox-vm.json
Changes:
* Updated NuGet packages.
* Added default values for image namespace, container registry username and password.
* Changed default Kubernetes version to `1.18.14` as `1.18.10` is no longer supported.
Fixes #1182
> IAI: Added default values for image namespace, container registry username and password.

- api/src/Microsoft.Azure.IIoT.Api/src/Publisher/Extensions/ModelExtensions.cs
- api/src/Microsoft.Azure.IIoT.OpcUa.Api/src/Core/Models/PendingAlarmsOptionsApiModel.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/NetworkMessageEncoder.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Engine/WriterGroupMessageSource.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/src/Models/DataSetMessageModel.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Edge.Publisher/tests/Storage/PublishedNodesJobConverterTests.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Models/SubscriptionNotificationModel.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Extensions/PublishedDataSetSourceModelEx.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa/src/Publisher/Models/Events/PendingAlarmsOptionsModel.cs
Added the ability to compress pending alarm messages if so desired, new setting CompressedPayload in PendingAlarmsOptionsModel
> Compress pending messages

- Industrial-IoT.sln
- common/src/Microsoft.Azure.IIoT.Hub.Mock/src/Services/IoTHubServices.cs
- modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/tests/IntegrationTests.cs
- modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/tests/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher.Tests.csproj
- modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/tests/OPCUAServerFixture.cs
- modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/tests/PublishedNodes/CanSendAlarmToIoTHubTest.json
- modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/tests/PublishedNodes/CanSendDataItemToIoTHubTest.json
- modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/tests/PublisherIntegrationTestBase.cs
Added initial core framework to provide starting point for integration test for publisher.
Some Features:
1. Using sample opcua servers and mocks in the existing codebase.
2. Minimal change to the existing codebase and no change in non mocking/testing codebase.
3. Sample tests to provide a starting point.
P.S. You may need to adapt it to your test cases e.g. add new node managers with specific use cases.
> Created integration tests framework, first cut.

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Stack/Encoders/Models/EncodeableDictionary.cs
fix: limiting the occurrences of null values in JSON output
> Don't output null values

- docs/opc-event-configuration.md
User guide for configuring for events
> User guide configuration for events

- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Services/SubscriptionServices.cs
fix: When receiving multiple events in the event callback, the code now sends them one-by-one through the processing pipeline.
> Send events one by one through the pipeline

- common/src/Microsoft.Azure.IIoT.Core/src/Deploy/ILogWorkspaceConfig.cs
- common/src/Microsoft.Azure.IIoT.Core/src/Deploy/Runtime/LogWorkspaceConfig.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Deploy/IoTHubDiscovererDeployment.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/src/Deploy/IoTHubMetricsCollectorDeployment.cs
- components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Registry/tests/Deploy/IoTHubMetricsCollectorDeploymentTests.cs
- services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry/src/Runtime/Config.cs
Update metrics collector to the released image
> Update metrics collector to the released image

- tools/e2etesting/steps/deployplatform.yml
- tools/e2etesting/steps/runtests.yml
Edit to add new key vault to replace the purged one for CI/CD pipeline for release and main branches.
> Edit to add new key vault to replace the purged one for CI/CD pipeline for release and main branches.

- tools/scripts/acr-build.ps1
*edit starts with in acr-build to capture 'releases' branch
> set 'releases' branch ready

- version.json
- Update release version to match LTS targeted release.
> Set release version for LTS 2.8.0

- tools/e2etesting/TestEventProcessor/TestEventProcessor.Businesslogic/TelemetryValidator.cs
- tools/e2etesting/TestEventProcessor/TestEventProcessor.Businesslogic/TestEventProcessor.Businesslogic.csproj
* And update test code to not spew warnings.
> Fix missed vulnerable package in test code dependency

- deploy/templates/azuredeploy.standard.json
Fixes issue #1129 
Rename TSI ID properties using Pascal Case & Timestamp property
> Fix TSI configuration settings

- azure-pipelines.yml
- deploy/src/Microsoft.Azure.IIoT.Deployment/Deployment/DeploymentExecutor.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Microsoft.Azure.IIoT.Deployment.csproj
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/ArmTemplates.Designer.cs
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/ArmTemplates.resx
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/deployments/jumpbox-vm-setup.json
- deploy/src/Microsoft.Azure.IIoT.Deployment/Resources/deployments/jumpbox-vm.json
- deploy/templates/azuredeploy.standard.json
- tools/e2etesting/TestEventProcessor/TestEventProcessor.Businesslogic/TelemetryValidator.cs
- tools/e2etesting/TestEventProcessor/TestEventProcessor.Businesslogic/TestEventProcessor.Businesslogic.csproj
- tools/e2etesting/pipeline_orchestrated.yml
- tools/e2etesting/pipeline_standalone.yml
- version.json
- Setting releases branch ready for release after a latest pull from main for remaining missing commits.
> Merge main into releases

- docs/opc-event-output.md
A guide detailing the output from events received in the publisher
> User Guide for output from events
